POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "Another Example",
    "author": "not bilal Abdelkadir",
    "url": "https://github.com/fullstack-hy2020/part3-notes-backend/blob/part4-2/index.js",
    "likes": 20
}